const db = require('../../../db/index');

const createApplication = (req, res) => {
  db.collection('cohorts')
    // add a new application with id generated by Firestore
    .add({ ...req.body })
    .then(docRef => {
      console.log('doc', docRef);
      res.status(201).json({
        id: docRef.id,
        message: 'Application successfully added to the database!',
      });
    })
    .catch(error => {
      res.json({ error });
    });
};

module.exports = {
  createApplication,
};
