const db = require('../../../db/index');
const { firestore } = require('firebase-admin');

const createApplication = (req, res) => {
  let { dateOpen, dateClosed, dateResponse } = req.body;

  // Convert the string date values into Timestamp objects.
  // Firebase will handle the rest.
  let [dateOpenTstamp, dateClosedTstamp, dateResponseTstamp] = [
    firestore.Timestamp.fromDate(new Date(dateOpen + 'T00:00:00')),
    firestore.Timestamp.fromDate(new Date(dateClosed + 'T00:00:00')),
    firestore.Timestamp.fromDate(new Date(dateResponse + 'T00:00:00')),
  ];

  const newBody = { ...req.body };
  newBody.dateOpen = dateOpenTstamp;
  newBody.dateClosed = dateClosedTstamp;
  newBody.dateResponse = dateResponseTstamp;

  db.collection('cohorts')
    // add a new application with id generated by Firestore
    .add({ ...newBody })
    .then(docRef => {
      console.log('doc', docRef);
      res.status(201).json({
        id: docRef.id,
        message: 'Application successfully added to the database!',
      });
    })
    .catch(error => {
      res.json({ error });
    });
};

module.exports = {
  createApplication,
};
