const db = require('../../../db/index');

const studentSubmission = (req, res) => {
  db.collection('studentSubmissions')
    // add a new application with id generated by Firestore
    .add({ ...req.body })
    .then(docRef => {
      res.status(201).json({
        id: docRef.id,
        message: `Application successfully added to the database!`,
      });
    })
    .catch(error => {
      console.log(error);
      res.status(500).json({
        message: 'Server error, submission was not sent.',
      });
    });
};

module.exports = {
  studentSubmission,
};
